server:
  port: 8083

spring:
  application:
    name: booking-service
  cloud:
    config:
      enabled: false
  datasource:
    url: jdbc:postgresql://localhost:5432/badminton_db?currentSchema=booking
    username: admin
    password: adminpassword
    driver-class-name: org.postgresql.Driver
  data:
    redis:
      host: localhost
      port: 6379
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  flyway:
    enabled: false
  kafka:
    bootstrap-servers: localhost:9094
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: booking-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
                    spring.json.trusted.packages: com.badminton.bookingservice.event,com.badminton.paymentservice.event

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: false
    instance-id: ${spring.application.name}:${server.port}
  client:
    register-with-eureka: true
    fetch-registry: true
    registry-fetch-interval-seconds: 5
    service-url:
      defaultZone: http://localhost:8761/eureka/

app:
  booking:
    cancel-before-hours: 24
  schema:
    auto-normalize: true
  services:
    venue-service:
      url: http://localhost:8082
  config:
    url: http://localhost:8080/identity/api/v1/config/public

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
  payment-service:
    url: http://localhost:8084
