ALTER TABLE booking.booking_items
ADD COLUMN IF NOT EXISTS booking_id UUID,
ADD COLUMN IF NOT EXISTS venue_id UUID,
ADD COLUMN IF NOT EXISTS court_id UUID,
ADD COLUMN IF NOT EXISTS court_name_snapshot VARCHAR(100),
ADD COLUMN IF NOT EXISTS start_time TIMESTAMP,
ADD COLUMN IF NOT EXISTS end_time TIMESTAMP,
ADD COLUMN IF NOT EXISTS created_at TIMESTAMP;
