ALTER TABLE booking.bookings
ADD COLUMN IF NOT EXISTS user_id UUID,
ADD COLUMN IF NOT EXISTS venue_id UUID,
ADD COLUMN IF NOT EXISTS venue_name_snapshot VARCHAR(255),
ADD COLUMN IF NOT EXISTS total_amount NUMERIC(12,2),
ADD COLUMN IF NOT EXISTS status VARCHAR(30),
ADD COLUMN IF NOT EXISTS payment_status VARCHAR(30),
ADD COLUMN IF NOT EXISTS expires_at TIMESTAMP,
ADD COLUMN IF NOT EXISTS paid_at TIMESTAMP,
ADD COLUMN IF NOT EXISTS created_at TIMESTAMP,
ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP;
