ALTER TABLE booking.bookings ADD COLUMN IF NOT EXISTS booking_date DATE NOT NULL DEFAULT CURRENT_DATE;
ALTER TABLE booking.bookings ADD COLUMN IF NOT EXISTS customer_name VARCHAR(200) NOT NULL DEFAULT '';
ALTER TABLE booking.bookings ADD COLUMN IF NOT EXISTS customer_email VARCHAR(200) NOT NULL DEFAULT '';
ALTER TABLE booking.bookings ADD COLUMN IF NOT EXISTS court_name VARCHAR(100) NOT NULL DEFAULT '';
ALTER TABLE booking.bookings ADD COLUMN IF NOT EXISTS court_type VARCHAR(50) NOT NULL DEFAULT '';
ALTER TABLE booking.bookings ADD COLUMN IF NOT EXISTS start_time TIMESTAMP NOT NULL DEFAULT NOW();
ALTER TABLE booking.bookings ADD COLUMN IF NOT EXISTS end_time TIMESTAMP NOT NULL DEFAULT NOW();
ALTER TABLE booking.bookings ADD COLUMN IF NOT EXISTS checked_in BOOLEAN DEFAULT FALSE;
