spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/badminton_db?currentSchema=venue
    username: admin
    password: adminpassword
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  kafka:
    bootstrap-servers: localhost:9094
    consumer:
      group-id: venue-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      # Sử dụng ErrorHandlingDeserializer để bao bọc lỗi giải mã
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        # Cấu hình class thực tế sẽ giải mã JSON
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.trusted.packages: "*"
        spring.json.value.default.type: "com.badminton.common.dto.event.OnboardingEvent"

server:
  port: 8082

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: false
    instance-id: ${spring.application.name}:${server.port}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

app:
  cloudinary:
    cloud-name: drq5f0hg2
    api-key: "318313767569946"
    api-secret: "Bvsb_Fx01DWD5qFC82Zf8IU-Uig"
