# yaml-language-server: $schema=https://www.schemastore.org/any.json
server:
  port: 8082

spring:
  application:
    name: venue-service
  datasource:
    url: jdbc:postgresql://localhost:5432/badminton_db?currentSchema=venue,public
    username: admin
    password: adminpassword
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.spatial.dialect.postgis.PostgisPG95Dialect
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
  flyway:
    enabled: true
    schemas: venue
    baseline-on-migrate: true
  kafka:
    bootstrap-servers: localhost:9094
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: venue-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        "[spring.deserializer.value.delegate.class]": org.springframework.kafka.support.serializer.JsonDeserializer
        "[spring.json.trusted.packages]": "*"
        "[spring.json.value.default.type]": "com.badminton.common.dto.event.OnboardingEvent"

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

app:
  services:
    booking-service:
      url: http://localhost:8083
  cloudinary:
    cloud-name: drq5f0hg2
    api-key: "318313767569946"
    api-secret: "Bvsb_Fx01DWD5qFC82Zf8IU-Uig"

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: false
    instance-id: ${spring.application.name}:${server.port}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
