server:
  port: 8087

spring:
  application:
    name: recommendation-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/recommendation_db
    redis:
      host: localhost
      port: 6379
      database: 2
  kafka:
    bootstrap-servers: localhost:9094
    consumer:
      group-id: recommendation-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: false
    instance-id: ${spring.application.name}:${server.port}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

# External service URLs
external:
  venue-service:
    url: http://localhost:8082
  community-service:
    url: http://localhost:8085