spring:
  application:
    name: identity-service
  profiles:
    active: dev
  config:
    import: "optional:configserver:http://localhost:8888"

server:
  forward-headers-strategy: framework

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: false
    instance-id: ${spring.application.name}:${server.port}
  client:
    register-with-eureka: true
    fetch-registry: true
    registry-fetch-interval-seconds: 5
    service-url:
      defaultZone: http://localhost:8761/eureka/

app:
  cloudinary:
    cloud-name: drq5f0hg2
    api-key: "318313767569946"
    api-secret: "Bvsb_Fx01DWD5qFC82Zf8IU-Uig"

