spring:
  application:
    name: identity-service
  profiles:
    active: dev
  cloud:
    config:
      enabled: false
      import-check:
        enabled: false
  datasource:
    url: jdbc:postgresql://localhost:5432/badminton_db?currentSchema=identity
    username: admin
    password: adminpassword
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  kafka:
    bootstrap-servers: localhost:9094
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: identity-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
  data:
    redis:
      host: localhost
      port: 6379
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${SPRING_MAIL_USERNAME:badminton.platform.noreply@gmail.com}
    password: ${SPRING_MAIL_PASSWORD:app_password}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  security:
    oauth2:
      authorizationserver:
        issuer: http://localhost:8081

server:
  port: 8081
  forward-headers-strategy: framework

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: false
    instance-id: ${spring.application.name}:${server.port}
  client:
    register-with-eureka: true
    fetch-registry: true
    registry-fetch-interval-seconds: 5
    service-url:
      defaultZone: http://localhost:8761/eureka/

jwt:
  signerKey: "zV9X7f6N8M2K5P4R1S3T0U9V8W7X6Y5Z4A3B2C1D0E9F8G7H6I5J4K3L2M1N0O9"
  valid-duration: 86400
  refreshable-duration: 604800

app:
  cloudinary:
    cloud-name: drq5f0hg2
    api-key: "318313767569946"
    api-secret: "Bvsb_Fx01DWD5qFC82Zf8IU-Uig"

management:
  health:
    mail:
      enabled: false
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,info
