spring:
  application:
    name: gateway-service
  profiles:
    active: dev
  cloud:
    config:
      enabled: false
    stream:
      kafka:
        binder:
          brokers: localhost:9094
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: identity-service
          uri: lb://identity-service
          predicates:
            - Path=/identity/**
          filters:
            - RewritePath=/identity/(?<path>.*), /$\{path}
        - id: venue-service
          uri: lb://venue-service
          predicates:
            - Path=/venues/**
          filters:
            - RewritePath=/venues/(?<path>.*), /$\{path}
        - id: booking-service
          uri: lb://booking-service
          predicates:
            - Path=/bookings/**
          filters:
            - RewritePath=/bookings/(?<path>.*), /$\{path}
        - id: payment-service
          uri: lb://payment-service
          predicates:
            - Path=/payments/**
          filters:
            - RewritePath=/payments/(?<path>.*), /$\{path}
        - id: community-service
          uri: lb://community-service
          predicates:
            - Path=/communities/**
          filters:
            - RewritePath=/communities/(?<path>.*), /$\{path}
        - id: chat-service
          uri: http://localhost:8686
          predicates:
            - Path=/chat/api/**
          filters:
            - RewritePath=/chat/api/(?<path>.*), /$\{path}

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081
  kafka:
    bootstrap-servers: localhost:9094

jwt:
  signerKey: "zV9X7f6N8M2K5P4R1S3T0U9V8W7X6Y5Z4A3B2C1D0E9F8G7H6I5J4K3L2M1N0O9"

auth:
  token-url: http://localhost:8080/identity/api/v1/auth/login
  scopes: openid, profile, email

server:
  port: 8080

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: false
    instance-id: ${spring.application.name}:${server.port}
  client:
    register-with-eureka: true
    fetch-registry: true
    registry-fetch-interval-seconds: 5
    service-url:
      defaultZone: http://localhost:8761/eureka/
